site_name: DapperDanDev
site_url: https://dapperdan.dev
site_description: A blog dedicated to software development, design patterns, and best practices.
theme:
  name: simple-blog
  custom_dir: overrides
  favicon: img/favicon.ico
  sidebar: true
  navigation_depth: 3
  highlightjs: false
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      noclasses: true
      pygments_style: dracula
  - pymdownx.superfences
  - meta
plugins:
  - search
  - awesome-pages
extra:
  header_nav:
    - Home
    - About
  social:
    - name: GitHub
      icon: fa fa-github
      link: https://github.com/dapperdandev
exclude_docs: |
  posts/drafts/
