name: Publish to Medium
on:
    push:
        branches: ['main']

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - id: files
              uses: jitterbit/get-changed-files@v1
            - id: posts
              name: Detecting posts from the changes
              run: |
                  i=0
                  for changed_file in ${{ steps.files.outputs.added_modified }}; do
                    echo "Do something with ${changed_file}."
                    if [[ "${changed_file}" == "posts"* ]];
                    then
                      echo "File ${changed_file} matched post."
                      echo "::set-output name=post${i}::${changed_file}"
                      ((i=i+1))
                    fi
                  done
            - if: steps.posts.outputs.post0
              name: Publish to medium
              # uses: infraway/post-medium-action@v1.6.0
              uses: dapperdandev/post-medium-action/main
              with:
                  access_token: ${{ secrets.MEDIUM_ACCESS_TOKEN }}
                  markdown_file: ${{ steps.posts.outputs.post0 }}
                  base_url: https://medium.com/@dapperdandev
